# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: setup-lua
      # You may pin to the exact commit or the version.
      uses: ljmf00/setup-lua@v.1.0.1
      with:
        # version of Lua to setup
        lua-version: 5.1
        # whether to install luarocks or not
        install-luarocks: false
          
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: setup-lua
      # You may pin to the exact commit or the version.
      uses: ljmf00/setup-lua@v.1.0.1
      with:
        # version of Lua to setup
        lua-version: 5.1
        # whether to install luarocks or not
        install-luarocks: false
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start && npm test
